-- INSERT INTO categories (`id`, `name`)  VALUES
'Remove the old car wreck'
'Asked to organize a hawker stall'
'Report the car that parks on the road'
'Ask to proceed with the person placing the barrier.'
'Requesting the removal of public intrusions'
'Request a parking waiver'
'Requesting grace to set things up'
'Ask to dredge the drain.'
'Ask to proceed with those who pour water, oil or discard the debris in the drain.'
'Ask to adjust the drain cap size'
'Requesting to adjust the level of the drainage pond to the road surface'
'Requesting a drainage pipe'
'Defective pipe cover'
'Drain cover disappeared'
'Ads'
'label'
'promise'
'Products that may be dangerous'
'Residual waste'
'Garbage dropped'
'Garbage smelly'
'Request to move the garbage dump point'
'Insufficient waste tank'
'Garbage is not on time'
'Garbage is not cheap'
'Water leaking waste'
'Garbage water flows into the groundwater'
'Release sewage into the sewers'
'Release sewage into public water sources'
'Garbage collector staff, not collect garbage'
'The store staff is not on time'
'There is no garbage tank for all type of waste'
'Overrate charging'
'Charge fees but no receipts'
'Charge fees in advance'
'Industrial factories dumping hazardous waste with household waste'
'Impersonating to charge the fee'
'Charge fees but no receipts'
'Request to proceed with the construct or extend the building without permission'
'Request to proceed with the construct or extend the building not not same as the permission'
'Please check Solve problems of damaged buildings, cracks or collapses. '
'Request to install And check the fire protection system and fire escape ladder '
'Requesting to install dust and drop protection devices'
'Request for electricity'
'Request to repair, change, add electrical wires and Light bulb'
'Requesting to correct the disorderly power lines or may cause harm to the people'
'Requesting to proceed with the smuggling use of electricity'
'Ask to turn off/on electricity.'
'Requesting to deal with material falling on the traffic surface'
'Asked to install, repair, move the curved glass'
'Request to install, repair, move, speed bumper'
'Requesting to install, repair, move, sign, traffic signs'
'Requesting to install, repair, move signs'
'Request to consider solving traffic congestion problems'
'Request to add a reversal point'
'Requesting to reduce the traffic island to expand the traffic surface'
'Request to connect the road'
'Requesting road construction'
'Requesting an extension of the road'
'Requesting road repairs'
'Request a road pavement.'
'Request to accelerate the construction speed of the road'
'Request to accelerate the repair speed of the road'
'Request to solve a problem in the park'
'Ask to trim the tree branches'
'Requesting tree maintenance'
'Ask to create a garden'
'Accuse the authorities'
'Ask for justice'
'Requesting sandbags for flood protection construction'
'Requesting a flood solution'
'Please close the floodgate.'
'Request to build a temporary pathway bridge'
'Request to pump the water out'
'Request to build a dam'
'Requesting to collect weeds in the canal'
'Requesting a solution to the dam breakdown problem'
'Requesting to solve the problem of stinking water'
'Requesting to dredge the canal'
'Requesting to remove footpath'
'Requesting to reduce the height of footpath'
'Requesting to increase the height of footpath'
'Requesting construction of a footpath'
'Requesting a repair of footpath'
'Request to accelerate the construction speed or repair speed of the footpath'
'Requesting a bridge construction'
'Requesting bridge repairs'
'Request to move a bridge'
'Requesting to speed up construction or repair the bridge'
'Requesting the construction of passenger accommodation'
'Requesting to move passengers accommodation'
'Requesting to repair the passenger accommodation'
'Please consider Edit ad images installed in the passenger accommodation area '
'Request a public phone'
'Request to organize a messy phone wire'
'Requesting to improve the conduit'
'Defective public phone'
'Move the phone booth'
'Request for water supply'
'Request to expand the plumbing'
'Request to install the red head plumbing'
'Requesting to accelerate construction, renovation or expansion of plumbing pipes'
'Request to accelerate the expansion of plumbing pipes'
'Report the broken pipe / not flow'
'Tap water does not flow or soft flow'
'Detainment'
'rape'
'old people'
'forsake'
'Abuse'
'Mayhem'
'Disadvantaged'
'mingle'
'Criminals'
'Student group fleeing school'
'Child quarrels'
'cigarette'
'Addictive substance'
'alcohol'
'Request to install bicycle parking'
'Nomadic person'
'motorbike taxi is not correct'
'Requesting assistance to Bangkok officials'
'Ask to perform a nomadic elephant'
'Requesting the collection of dead animals'
'Found a venomous snake or varanus'
'Garbage truck leak wastewater'
'Defective floodgate'
'House pillars, buildings, damaged scaffolding'
'Fire grass'
'chemicals'
'Moving the galvanized sheet / roof of the house'
'Damaged passenger accommodation'
'smell'
'Drainage into the streets or houses of others'
'Requesting action with dogs, rats, mosquitoes, pigeons'
'Request to check the use and storage of chemicals'
'smoke'
'dust'
'the sound'
'Insects or poisonous animals'
'Arson threat, threatening, assaulting'
'Collapsed building'
'sabotage'
'Collect weapons, transfer weapons'
'accident'
'Emergency illness'
'The bomb threat'
'Security reason'
'Fire incident'
'Building, building or large building falling'
'rally or rioting'
'Explosion incident'