INSERT INTO categories (`name`)  VALUES
('Remove the old car wreck'),
('Ask to dredge the drain.'),
('Products that may be dangerous'),
'Garbage dropped'
'Garbage smelly'
'Insufficient waste tank'
'Request to repair, change, add electrical wires and Light bulb'
'Requesting to install, repair, move, sign, traffic signs'
'Requesting road repairs'
'Requesting tree maintenance'
'Requesting to collect weeds in the canal'
'Request to organize a messy phone wire'
'Report the broken pipe / not flow'
'Tap water does not flow or soft flow'
'Forsake'
'Criminals'
'Student group fleeing school'
'Child quarrels'
'Addictive substance'
'Alcohol'
'Nomadic person'
'Requesting the collection of dead animals'
'Found a venomous snake or varanus'
'House pillars, buildings, damaged scaffolding'
'chemicals'
'Drainage into the streets or houses of others'
'Requesting action with dogs, rats, mosquitoes, pigeons'
'Request to check the use and storage of chemicals'
'smoke'
'dust'
'the sound'
'Insects or poisonous animals'
'Arson threat, threatening, assaulting'
'Collapsed building'
'sabotage'
'Collect weapons, transfer weapons'
'accident'
'Emergency illness'
'The bomb threat'
'Security reason'
'Fire incident'
'Building, building or large building falling'
'rally or rioting'
'Explosion incident'