INSERT INTO categories (`name`)  VALUES
('Remove the old car wreck'),
('Ask to dredge the drain.'),
('Products that may be dangerous'),
'Garbage dropped'
'Garbage smelly'
'Insufficient waste tank'
'Request to repair, change, add electrical wires and Light bulb'
'Requesting to install, repair, move, sign, traffic signs'
'Requesting road repairs'
'Requesting tree maintenance'
'Requesting to collect weeds in the canal'
'Request to organize a messy phone wire'
'Report the broken pipe / not flow'
'Tap water does not flow or soft flow'
'Forsake'
'Criminals'
'Student group fleeing school'
'Child quarrels'
'Addictive substance'
'Alcohol'
'Nomadic person'
'Requesting the collection of dead animals'
'Found a venomous snake or varanus'
'House pillars, buildings, damaged scaffolding'
'chemicals'
'Drainage into the streets or houses of others'
'Requesting action with dogs, rats, mosquitoes, pigeons'
'the sound'
'Collapsed building'
'Collect weapons, transfer weapons'
'Accident'
'Security reason'
'Fire incident'
'rally or rioting'
'Explosion incident'
